##
## Build
##

FROM golang:1.16-buster AS build

WORKDIR /app

COPY ../src/go.mod ./
COPY ../src/go.sum ./
RUN go mod download

COPY ../src/*.go ./

RUN go build -o /ddpai-downloader

##
## Deploy
##

FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /ddpai-downloader /ddpai-downloader

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/ddpai-downloader"]